version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: forall
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 503812
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/forall
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 503812
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
