spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/forall
    username: postgres
    password: 503812
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect